# Generated by Django 3.2.4 on 2021-06-22 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsNew',
            fields=[
                ('id_cars', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dealership', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
