# Generated by Django 3.2.4 on 2021-06-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsnew',
            name='image',
            field=models.ImageField(blank=True, upload_to='cars/%Y/%m/%d'),
        ),
    ]
